-- Números de WhatsApp "de equipo": teléfonos libres (no ligados a
-- workspace_members) que, si el workspace tiene include_team_numbers=true,
-- se agregan automáticamente como destinatarios de TODA campaña nueva.

BEGIN;

CREATE TABLE IF NOT EXISTS team_numbers (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    telefono     TEXT NOT NULL,
    etiqueta     TEXT NOT NULL,
    created_at   TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (workspace_id, telefono)
);
CREATE INDEX IF NOT EXISTS idx_team_numbers_workspace ON team_numbers(workspace_id);

ALTER TABLE team_numbers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "ws_member_team_numbers" ON team_numbers;
CREATE POLICY "ws_member_team_numbers" ON team_numbers
    FOR ALL USING (
        workspace_id IN (SELECT workspace_id FROM workspace_members WHERE user_id = auth.uid())
    )
    WITH CHECK (
        workspace_id IN (SELECT workspace_id FROM workspace_members WHERE user_id = auth.uid())
    );

ALTER TABLE app_settings
    ADD COLUMN IF NOT EXISTS include_team_numbers BOOLEAN NOT NULL DEFAULT false;

COMMIT;
