-- ─────────────────────────────────────────────
-- WA Campaigns — Supabase Schema
-- Ejecuta esto en Supabase > SQL Editor
-- ─────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS contacts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telefono   TEXT    NOT NULL UNIQUE,
    nombre     TEXT,
    etiqueta   TEXT,                        -- legacy single-tag (kept for backward compat)
    tags       TEXT[]  DEFAULT '{}',        -- multi-tag array (primary)
    created_at    TIMESTAMPTZ DEFAULT NOW(),
    last_sent_at  TIMESTAMPTZ,
    last_template TEXT
);
CREATE INDEX IF NOT EXISTS idx_contacts_telefono ON contacts(telefono);
CREATE INDEX IF NOT EXISTS idx_contacts_etiqueta ON contacts(etiqueta);
CREATE INDEX IF NOT EXISTS idx_contacts_tags     ON contacts USING GIN(tags);

-- Función RPC: devuelve todas las etiquetas únicas con conteo de contactos
CREATE OR REPLACE FUNCTION get_all_tags_with_counts()
RETURNS TABLE(tag TEXT, cnt BIGINT) LANGUAGE sql AS $$
  SELECT t.tag, COUNT(*) AS cnt
  FROM contacts, unnest(tags) AS t(tag)
  WHERE t.tag IS NOT NULL AND t.tag <> ''
  GROUP BY t.tag
  ORDER BY t.tag;
$$;

-- Migración de datos (ejecutar una vez si la tabla ya existe con datos):
-- ALTER TABLE contacts ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}';
-- UPDATE contacts SET tags = ARRAY[etiqueta] WHERE etiqueta IS NOT NULL AND (tags IS NULL OR tags = '{}');

CREATE TABLE IF NOT EXISTS campaigns (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre            TEXT    NOT NULL,
    template_name     TEXT    NOT NULL,
    template_language TEXT    NOT NULL DEFAULT 'es',
    template_params   JSONB            DEFAULT '[]',
    status            TEXT    NOT NULL DEFAULT 'draft',
    total             INT     NOT NULL DEFAULT 0,
    enviados          INT     NOT NULL DEFAULT 0,
    entregados        INT     NOT NULL DEFAULT 0,
    leidos            INT     NOT NULL DEFAULT 0,
    fallidos          INT     NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ DEFAULT NOW(),
    started_at        TIMESTAMPTZ,
    completed_at      TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS campaign_messages (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id   BIGINT  NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
    telefono      TEXT    NOT NULL,
    wa_message_id TEXT,
    status        TEXT    NOT NULL DEFAULT 'pending',
    error         TEXT,
    sent_at       TIMESTAMPTZ,
    delivered_at  TIMESTAMPTZ,
    read_at       TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_cm_campaign  ON campaign_messages(campaign_id);
CREATE INDEX IF NOT EXISTS idx_cm_wa_id    ON campaign_messages(wa_message_id);
CREATE INDEX IF NOT EXISTS idx_cm_status   ON campaign_messages(campaign_id, status);

-- ─── Habilitar Realtime ────────────────────────
ALTER PUBLICATION supabase_realtime ADD TABLE campaigns;
ALTER PUBLICATION supabase_realtime ADD TABLE campaign_messages;

-- ─── Row Level Security ───────────────────────────────────────
ALTER TABLE contacts          ENABLE ROW LEVEL SECURITY;
ALTER TABLE campaigns         ENABLE ROW LEVEL SECURITY;
ALTER TABLE campaign_messages ENABLE ROW LEVEL SECURITY;

-- Cada usuario solo accede a sus propios contactos y campañas.
-- Las funciones serverless usan el service_role key (bypassa RLS),
-- por lo que estas políticas protegen el acceso directo con anon/user key.
CREATE POLICY "own_contacts" ON contacts
    FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "own_campaigns" ON campaigns
    FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- campaign_messages hereda el aislamiento a través de la FK a campaigns
CREATE POLICY "own_campaign_messages" ON campaign_messages
    FOR ALL USING (
        campaign_id IN (
            SELECT id FROM campaigns WHERE user_id = auth.uid()
        )
    )
    WITH CHECK (
        campaign_id IN (
            SELECT id FROM campaigns WHERE user_id = auth.uid()
        )
    );

-- Migración: si ya existen las políticas "allow_all", eliminarlas primero:
-- DROP POLICY IF EXISTS "allow_all" ON contacts;
-- DROP POLICY IF EXISTS "allow_all" ON campaigns;
-- DROP POLICY IF EXISTS "allow_all" ON campaign_messages;

-- ─────────────────────────────────────────────
-- WORKSPACES — Migración (ejecutar en Supabase SQL Editor)
-- ─────────────────────────────────────────────

-- 1. Tabla de workspaces (una por cuenta/cliente del usuario)
CREATE TABLE IF NOT EXISTS workspaces (
    id         UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id    UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name       TEXT        NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_workspaces_user_id ON workspaces(user_id);

ALTER TABLE workspaces ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own_workspaces" ON workspaces
    FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- 2. Agregar workspace_id a las tablas existentes
ALTER TABLE contacts          ADD COLUMN IF NOT EXISTS workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE;
ALTER TABLE campaigns         ADD COLUMN IF NOT EXISTS workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE;

-- 3. Tabla app_settings con workspace_id
CREATE TABLE IF NOT EXISTS app_settings (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                UUID,
    workspace_id           UUID REFERENCES workspaces(id) ON DELETE CASCADE,
    wa_access_token        TEXT,
    wa_phone_number_id     TEXT,
    wa_business_account_id TEXT,
    updated_at             TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (workspace_id)
);

-- 4. Migración de datos existentes:
-- Crea el workspace "Dominos" para tu usuario y asigna todos los datos existentes.
-- Reemplaza <TU_USER_ID> con tu UUID de Supabase auth.users.
--
-- DO $$
-- DECLARE
--   ws_id UUID;
--   u_id  UUID := '<TU_USER_ID>';
-- BEGIN
--   INSERT INTO workspaces (user_id, name) VALUES (u_id, 'Dominos')
--   RETURNING id INTO ws_id;
--
--   UPDATE contacts  SET workspace_id = ws_id WHERE user_id = u_id;
--   UPDATE campaigns SET workspace_id = ws_id WHERE user_id = u_id;
--   UPDATE app_settings SET workspace_id = ws_id WHERE user_id = u_id;
-- END $$;

-- 5. Índices de workspace_id
CREATE INDEX IF NOT EXISTS idx_contacts_workspace  ON contacts(workspace_id);
CREATE INDEX IF NOT EXISTS idx_campaigns_workspace ON campaigns(workspace_id);

-- 6. Función RPC actualizada: etiquetas por workspace
CREATE OR REPLACE FUNCTION get_all_tags_with_counts(p_workspace_id UUID DEFAULT NULL)
RETURNS TABLE(tag TEXT, cnt BIGINT) LANGUAGE sql AS $$
  SELECT t.tag, COUNT(*) AS cnt
  FROM contacts, unnest(tags) AS t(tag)
  WHERE t.tag IS NOT NULL AND t.tag <> ''
    AND (p_workspace_id IS NULL OR workspace_id = p_workspace_id)
  GROUP BY t.tag
  ORDER BY t.tag;
$$;

-- ─── Funciones RPC para contadores atómicos ────
CREATE OR REPLACE FUNCTION increment_campaign_sent(campaign_id BIGINT)
RETURNS void LANGUAGE sql AS $$
  UPDATE campaigns SET enviados = enviados + 1 WHERE id = campaign_id;
$$;

CREATE OR REPLACE FUNCTION increment_campaign_failed(campaign_id BIGINT)
RETURNS void LANGUAGE sql AS $$
  UPDATE campaigns SET fallidos = fallidos + 1 WHERE id = campaign_id;
$$;

CREATE OR REPLACE FUNCTION increment_campaign_delivered(campaign_id BIGINT)
RETURNS void LANGUAGE sql AS $$
  UPDATE campaigns SET entregados = entregados + 1 WHERE id = campaign_id;
$$;

CREATE OR REPLACE FUNCTION increment_campaign_read(campaign_id BIGINT)
RETURNS void LANGUAGE sql AS $$
  UPDATE campaigns SET leidos = leidos + 1 WHERE id = campaign_id;
$$;

-- ──────────────────────────────────────────────────────────────────────────────
-- Siguientes migraciones (NO incluidas en este archivo, ejecutar por separado):
--
-- 0002_workspace_members.sql — multi-usuario por workspace. Introduce la tabla
--   workspace_members(workspace_id, user_id, role) y reescribe las políticas
--   RLS para que el acceso a contacts/campaigns/app_settings se base en
--   membresía en lugar de user_id. Backfill del dueño actual como 'owner'.
--
-- 0003_template_media_storage.sql — bucket público "template-media" para
--   imágenes de header de plantillas WhatsApp (5 MB, PNG/JPG). RLS para
--   uploads via anon key gated por membresía. Lectura pública (Meta debe
--   poder descargarlas sin auth).
--   (Nota: el endpoint /api/uploads/image se añade en PR aparte. El bucket
--   ya está creado en producción.)
--
-- 0004_workspace_members_rls_fix.sql — policy SELECT "self_membership" en
--   workspace_members. Sin ella, los subqueries de policies de otras tablas
--   devolvían 0 rows desde el browser y rompían el envío de campañas.
--
-- 0005_scheduling.sql — campaigns.scheduled_for + campaign_messages.claimed_at
--   + RPCs claim_pending_messages / rescue_stuck_claims. Soporta el worker
--   server-side que corre cada 1 min en Railway cron service.
-- ──────────────────────────────────────────────────────────────────────────────
