-- ─────────────────────────────────────────────
-- WA Campaigns — Supabase Schema
-- Ejecuta esto en Supabase > SQL Editor
-- ─────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS contacts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telefono   TEXT    NOT NULL UNIQUE,
    nombre     TEXT,
    etiqueta   TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_contacts_telefono ON contacts(telefono);
CREATE INDEX IF NOT EXISTS idx_contacts_etiqueta ON contacts(etiqueta);

CREATE TABLE IF NOT EXISTS campaigns (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre            TEXT    NOT NULL,
    template_name     TEXT    NOT NULL,
    template_language TEXT    NOT NULL DEFAULT 'es',
    template_params   JSONB            DEFAULT '[]',
    status            TEXT    NOT NULL DEFAULT 'draft',
    total             INT     NOT NULL DEFAULT 0,
    enviados          INT     NOT NULL DEFAULT 0,
    entregados        INT     NOT NULL DEFAULT 0,
    leidos            INT     NOT NULL DEFAULT 0,
    fallidos          INT     NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ DEFAULT NOW(),
    started_at        TIMESTAMPTZ,
    completed_at      TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS campaign_messages (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id   BIGINT  NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
    telefono      TEXT    NOT NULL,
    wa_message_id TEXT,
    status        TEXT    NOT NULL DEFAULT 'pending',
    error         TEXT,
    sent_at       TIMESTAMPTZ,
    delivered_at  TIMESTAMPTZ,
    read_at       TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_cm_campaign  ON campaign_messages(campaign_id);
CREATE INDEX IF NOT EXISTS idx_cm_wa_id    ON campaign_messages(wa_message_id);
CREATE INDEX IF NOT EXISTS idx_cm_status   ON campaign_messages(campaign_id, status);

-- ─── Habilitar Realtime ────────────────────────
ALTER PUBLICATION supabase_realtime ADD TABLE campaigns;
ALTER PUBLICATION supabase_realtime ADD TABLE campaign_messages;

-- ─── Row Level Security (acceso total para esta app admin) ───
ALTER TABLE contacts          ENABLE ROW LEVEL SECURITY;
ALTER TABLE campaigns         ENABLE ROW LEVEL SECURITY;
ALTER TABLE campaign_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow_all" ON contacts          FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all" ON campaigns         FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all" ON campaign_messages FOR ALL USING (true) WITH CHECK (true);

-- ─── Funciones RPC para contadores atómicos ────
CREATE OR REPLACE FUNCTION increment_campaign_sent(campaign_id BIGINT)
RETURNS void LANGUAGE sql AS $$
  UPDATE campaigns SET enviados = enviados + 1 WHERE id = campaign_id;
$$;

CREATE OR REPLACE FUNCTION increment_campaign_failed(campaign_id BIGINT)
RETURNS void LANGUAGE sql AS $$
  UPDATE campaigns SET fallidos = fallidos + 1 WHERE id = campaign_id;
$$;

CREATE OR REPLACE FUNCTION increment_campaign_delivered(campaign_id BIGINT)
RETURNS void LANGUAGE sql AS $$
  UPDATE campaigns SET entregados = entregados + 1 WHERE id = campaign_id;
$$;

CREATE OR REPLACE FUNCTION increment_campaign_read(campaign_id BIGINT)
RETURNS void LANGUAGE sql AS $$
  UPDATE campaigns SET leidos = leidos + 1 WHERE id = campaign_id;
$$;
