-- ─────────────────────────────────────────────
-- WA Campaigns — Supabase Schema
-- Ejecuta esto en Supabase > SQL Editor
-- ─────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS contacts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telefono   TEXT    NOT NULL UNIQUE,
    nombre     TEXT,
    etiqueta   TEXT,                        -- legacy single-tag (kept for backward compat)
    tags       TEXT[]  DEFAULT '{}',        -- multi-tag array (primary)
    created_at    TIMESTAMPTZ DEFAULT NOW(),
    last_sent_at  TIMESTAMPTZ,
    last_template TEXT
);
CREATE INDEX IF NOT EXISTS idx_contacts_telefono ON contacts(telefono);
CREATE INDEX IF NOT EXISTS idx_contacts_etiqueta ON contacts(etiqueta);
CREATE INDEX IF NOT EXISTS idx_contacts_tags     ON contacts USING GIN(tags);

-- Función RPC: devuelve todas las etiquetas únicas con conteo de contactos
CREATE OR REPLACE FUNCTION get_all_tags_with_counts()
RETURNS TABLE(tag TEXT, cnt BIGINT) LANGUAGE sql AS $$
  SELECT t.tag, COUNT(*) AS cnt
  FROM contacts, unnest(tags) AS t(tag)
  WHERE t.tag IS NOT NULL AND t.tag <> ''
  GROUP BY t.tag
  ORDER BY t.tag;
$$;

-- Migración de datos (ejecutar una vez si la tabla ya existe con datos):
-- ALTER TABLE contacts ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}';
-- UPDATE contacts SET tags = ARRAY[etiqueta] WHERE etiqueta IS NOT NULL AND (tags IS NULL OR tags = '{}');

CREATE TABLE IF NOT EXISTS campaigns (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre            TEXT    NOT NULL,
    template_name     TEXT    NOT NULL,
    template_language TEXT    NOT NULL DEFAULT 'es',
    template_params   JSONB            DEFAULT '[]',
    status            TEXT    NOT NULL DEFAULT 'draft',
    total             INT     NOT NULL DEFAULT 0,
    enviados          INT     NOT NULL DEFAULT 0,
    entregados        INT     NOT NULL DEFAULT 0,
    leidos            INT     NOT NULL DEFAULT 0,
    fallidos          INT     NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ DEFAULT NOW(),
    started_at        TIMESTAMPTZ,
    completed_at      TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS campaign_messages (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id   BIGINT  NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
    telefono      TEXT    NOT NULL,
    wa_message_id TEXT,
    status        TEXT    NOT NULL DEFAULT 'pending',
    error         TEXT,
    sent_at       TIMESTAMPTZ,
    delivered_at  TIMESTAMPTZ,
    read_at       TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_cm_campaign  ON campaign_messages(campaign_id);
CREATE INDEX IF NOT EXISTS idx_cm_wa_id    ON campaign_messages(wa_message_id);
CREATE INDEX IF NOT EXISTS idx_cm_status   ON campaign_messages(campaign_id, status);

-- ─── Habilitar Realtime ────────────────────────
ALTER PUBLICATION supabase_realtime ADD TABLE campaigns;
ALTER PUBLICATION supabase_realtime ADD TABLE campaign_messages;

-- ─── Row Level Security ───────────────────────────────────────
ALTER TABLE contacts          ENABLE ROW LEVEL SECURITY;
ALTER TABLE campaigns         ENABLE ROW LEVEL SECURITY;
ALTER TABLE campaign_messages ENABLE ROW LEVEL SECURITY;

-- Cada usuario solo accede a sus propios contactos y campañas.
-- Las funciones serverless usan el service_role key (bypassa RLS),
-- por lo que estas políticas protegen el acceso directo con anon/user key.
CREATE POLICY "own_contacts" ON contacts
    FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "own_campaigns" ON campaigns
    FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- campaign_messages hereda el aislamiento a través de la FK a campaigns
CREATE POLICY "own_campaign_messages" ON campaign_messages
    FOR ALL USING (
        campaign_id IN (
            SELECT id FROM campaigns WHERE user_id = auth.uid()
        )
    )
    WITH CHECK (
        campaign_id IN (
            SELECT id FROM campaigns WHERE user_id = auth.uid()
        )
    );

-- Migración: si ya existen las políticas "allow_all", eliminarlas primero:
-- DROP POLICY IF EXISTS "allow_all" ON contacts;
-- DROP POLICY IF EXISTS "allow_all" ON campaigns;
-- DROP POLICY IF EXISTS "allow_all" ON campaign_messages;

-- ─── Funciones RPC para contadores atómicos ────
CREATE OR REPLACE FUNCTION increment_campaign_sent(campaign_id BIGINT)
RETURNS void LANGUAGE sql AS $$
  UPDATE campaigns SET enviados = enviados + 1 WHERE id = campaign_id;
$$;

CREATE OR REPLACE FUNCTION increment_campaign_failed(campaign_id BIGINT)
RETURNS void LANGUAGE sql AS $$
  UPDATE campaigns SET fallidos = fallidos + 1 WHERE id = campaign_id;
$$;

CREATE OR REPLACE FUNCTION increment_campaign_delivered(campaign_id BIGINT)
RETURNS void LANGUAGE sql AS $$
  UPDATE campaigns SET entregados = entregados + 1 WHERE id = campaign_id;
$$;

CREATE OR REPLACE FUNCTION increment_campaign_read(campaign_id BIGINT)
RETURNS void LANGUAGE sql AS $$
  UPDATE campaigns SET leidos = leidos + 1 WHERE id = campaign_id;
$$;
